//! This submodule contains some helper function to validate Bible references

use crate::bible::{BibleBook, BibleChapter, BibleVerse};

pub fn validate_book_chapter_verse(book: &BibleBook, chapter: &BibleChapter, verse: &BibleVerse) -> bool {
    if book==&BibleBook::Genesis && *chapter==1 && *verse <= 31 { true }
    else if book==&BibleBook::Genesis && *chapter==2 && *verse <= 25 { true }
    else if book==&BibleBook::Genesis && *chapter==3 && *verse <= 24 { true }
    else if book==&BibleBook::Genesis && *chapter==4 && *verse <= 26 { true }
    else if book==&BibleBook::Genesis && *chapter==5 && *verse <= 32 { true }
    else if book==&BibleBook::Genesis && *chapter==6 && *verse <= 22 { true }
    else if book==&BibleBook::Genesis && *chapter==7 && *verse <= 24 { true }
    else if book==&BibleBook::Genesis && *chapter==8 && *verse <= 22 { true }
    else if book==&BibleBook::Genesis && *chapter==9 && *verse <= 29 { true }
    else if book==&BibleBook::Genesis && *chapter==10 && *verse <= 32 { true }
    else if book==&BibleBook::Genesis && *chapter==11 && *verse <= 32 { true }
    else if book==&BibleBook::Genesis && *chapter==12 && *verse <= 20 { true }
    else if book==&BibleBook::Genesis && *chapter==13 && *verse <= 18 { true }
    else if book==&BibleBook::Genesis && *chapter==14 && *verse <= 24 { true }
    else if book==&BibleBook::Genesis && *chapter==15 && *verse <= 21 { true }
    else if book==&BibleBook::Genesis && *chapter==16 && *verse <= 16 { true }
    else if book==&BibleBook::Genesis && *chapter==17 && *verse <= 27 { true }
    else if book==&BibleBook::Genesis && *chapter==18 && *verse <= 33 { true }
    else if book==&BibleBook::Genesis && *chapter==19 && *verse <= 38 { true }
    else if book==&BibleBook::Genesis && *chapter==20 && *verse <= 18 { true }
    else if book==&BibleBook::Genesis && *chapter==21 && *verse <= 34 { true }
    else if book==&BibleBook::Genesis && *chapter==22 && *verse <= 24 { true }
    else if book==&BibleBook::Genesis && *chapter==23 && *verse <= 20 { true }
    else if book==&BibleBook::Genesis && *chapter==24 && *verse <= 67 { true }
    else if book==&BibleBook::Genesis && *chapter==25 && *verse <= 34 { true }
    else if book==&BibleBook::Genesis && *chapter==26 && *verse <= 35 { true }
    else if book==&BibleBook::Genesis && *chapter==27 && *verse <= 46 { true }
    else if book==&BibleBook::Genesis && *chapter==28 && *verse <= 22 { true }
    else if book==&BibleBook::Genesis && *chapter==29 && *verse <= 35 { true }
    else if book==&BibleBook::Genesis && *chapter==30 && *verse <= 43 { true }
    else if book==&BibleBook::Genesis && *chapter==31 && *verse <= 55 { true }
    else if book==&BibleBook::Genesis && *chapter==32 && *verse <= 32 { true }
    else if book==&BibleBook::Genesis && *chapter==33 && *verse <= 20 { true }
    else if book==&BibleBook::Genesis && *chapter==34 && *verse <= 31 { true }
    else if book==&BibleBook::Genesis && *chapter==35 && *verse <= 29 { true }
    else if book==&BibleBook::Genesis && *chapter==36 && *verse <= 43 { true }
    else if book==&BibleBook::Genesis && *chapter==37 && *verse <= 36 { true }
    else if book==&BibleBook::Genesis && *chapter==38 && *verse <= 30 { true }
    else if book==&BibleBook::Genesis && *chapter==39 && *verse <= 23 { true }
    else if book==&BibleBook::Genesis && *chapter==40 && *verse <= 23 { true }
    else if book==&BibleBook::Genesis && *chapter==41 && *verse <= 57 { true }
    else if book==&BibleBook::Genesis && *chapter==42 && *verse <= 38 { true }
    else if book==&BibleBook::Genesis && *chapter==43 && *verse <= 34 { true }
    else if book==&BibleBook::Genesis && *chapter==44 && *verse <= 34 { true }
    else if book==&BibleBook::Genesis && *chapter==45 && *verse <= 28 { true }
    else if book==&BibleBook::Genesis && *chapter==46 && *verse <= 34 { true }
    else if book==&BibleBook::Genesis && *chapter==47 && *verse <= 31 { true }
    else if book==&BibleBook::Genesis && *chapter==48 && *verse <= 22 { true }
    else if book==&BibleBook::Genesis && *chapter==49 && *verse <= 33 { true }
    else if book==&BibleBook::Genesis && *chapter==50 && *verse <= 26 { true }
    else if book==&BibleBook::Exodus && *chapter==1 && *verse <= 22 { true }
    else if book==&BibleBook::Exodus && *chapter==2 && *verse <= 25 { true }
    else if book==&BibleBook::Exodus && *chapter==3 && *verse <= 22 { true }
    else if book==&BibleBook::Exodus && *chapter==4 && *verse <= 31 { true }
    else if book==&BibleBook::Exodus && *chapter==5 && *verse <= 23 { true }
    else if book==&BibleBook::Exodus && *chapter==6 && *verse <= 30 { true }
    else if book==&BibleBook::Exodus && *chapter==7 && *verse <= 25 { true }
    else if book==&BibleBook::Exodus && *chapter==8 && *verse <= 32 { true }
    else if book==&BibleBook::Exodus && *chapter==9 && *verse <= 35 { true }
    else if book==&BibleBook::Exodus && *chapter==10 && *verse <= 29 { true }
    else if book==&BibleBook::Exodus && *chapter==11 && *verse <= 10 { true }
    else if book==&BibleBook::Exodus && *chapter==12 && *verse <= 51 { true }
    else if book==&BibleBook::Exodus && *chapter==13 && *verse <= 22 { true }
    else if book==&BibleBook::Exodus && *chapter==14 && *verse <= 31 { true }
    else if book==&BibleBook::Exodus && *chapter==15 && *verse <= 27 { true }
    else if book==&BibleBook::Exodus && *chapter==16 && *verse <= 36 { true }
    else if book==&BibleBook::Exodus && *chapter==17 && *verse <= 16 { true }
    else if book==&BibleBook::Exodus && *chapter==18 && *verse <= 27 { true }
    else if book==&BibleBook::Exodus && *chapter==19 && *verse <= 25 { true }
    else if book==&BibleBook::Exodus && *chapter==20 && *verse <= 26 { true }
    else if book==&BibleBook::Exodus && *chapter==21 && *verse <= 36 { true }
    else if book==&BibleBook::Exodus && *chapter==22 && *verse <= 31 { true }
    else if book==&BibleBook::Exodus && *chapter==23 && *verse <= 33 { true }
    else if book==&BibleBook::Exodus && *chapter==24 && *verse <= 18 { true }
    else if book==&BibleBook::Exodus && *chapter==25 && *verse <= 40 { true }
    else if book==&BibleBook::Exodus && *chapter==26 && *verse <= 37 { true }
    else if book==&BibleBook::Exodus && *chapter==27 && *verse <= 21 { true }
    else if book==&BibleBook::Exodus && *chapter==28 && *verse <= 43 { true }
    else if book==&BibleBook::Exodus && *chapter==29 && *verse <= 46 { true }
    else if book==&BibleBook::Exodus && *chapter==30 && *verse <= 38 { true }
    else if book==&BibleBook::Exodus && *chapter==31 && *verse <= 18 { true }
    else if book==&BibleBook::Exodus && *chapter==32 && *verse <= 35 { true }
    else if book==&BibleBook::Exodus && *chapter==33 && *verse <= 23 { true }
    else if book==&BibleBook::Exodus && *chapter==34 && *verse <= 35 { true }
    else if book==&BibleBook::Exodus && *chapter==35 && *verse <= 35 { true }
    else if book==&BibleBook::Exodus && *chapter==36 && *verse <= 38 { true }
    else if book==&BibleBook::Exodus && *chapter==37 && *verse <= 29 { true }
    else if book==&BibleBook::Exodus && *chapter==38 && *verse <= 31 { true }
    else if book==&BibleBook::Exodus && *chapter==39 && *verse <= 43 { true }
    else if book==&BibleBook::Exodus && *chapter==40 && *verse <= 38 { true }
    else if book==&BibleBook::Leviticus && *chapter==1 && *verse <= 17 { true }
    else if book==&BibleBook::Leviticus && *chapter==2 && *verse <= 16 { true }
    else if book==&BibleBook::Leviticus && *chapter==3 && *verse <= 17 { true }
    else if book==&BibleBook::Leviticus && *chapter==4 && *verse <= 35 { true }
    else if book==&BibleBook::Leviticus && *chapter==5 && *verse <= 19 { true }
    else if book==&BibleBook::Leviticus && *chapter==6 && *verse <= 30 { true }
    else if book==&BibleBook::Leviticus && *chapter==7 && *verse <= 38 { true }
    else if book==&BibleBook::Leviticus && *chapter==8 && *verse <= 36 { true }
    else if book==&BibleBook::Leviticus && *chapter==9 && *verse <= 24 { true }
    else if book==&BibleBook::Leviticus && *chapter==10 && *verse <= 20 { true }
    else if book==&BibleBook::Leviticus && *chapter==11 && *verse <= 47 { true }
    else if book==&BibleBook::Leviticus && *chapter==12 && *verse <= 8 { true }
    else if book==&BibleBook::Leviticus && *chapter==13 && *verse <= 59 { true }
    else if book==&BibleBook::Leviticus && *chapter==14 && *verse <= 57 { true }
    else if book==&BibleBook::Leviticus && *chapter==15 && *verse <= 33 { true }
    else if book==&BibleBook::Leviticus && *chapter==16 && *verse <= 34 { true }
    else if book==&BibleBook::Leviticus && *chapter==17 && *verse <= 16 { true }
    else if book==&BibleBook::Leviticus && *chapter==18 && *verse <= 30 { true }
    else if book==&BibleBook::Leviticus && *chapter==19 && *verse <= 37 { true }
    else if book==&BibleBook::Leviticus && *chapter==20 && *verse <= 27 { true }
    else if book==&BibleBook::Leviticus && *chapter==21 && *verse <= 24 { true }
    else if book==&BibleBook::Leviticus && *chapter==22 && *verse <= 33 { true }
    else if book==&BibleBook::Leviticus && *chapter==23 && *verse <= 44 { true }
    else if book==&BibleBook::Leviticus && *chapter==24 && *verse <= 23 { true }
    else if book==&BibleBook::Leviticus && *chapter==25 && *verse <= 55 { true }
    else if book==&BibleBook::Leviticus && *chapter==26 && *verse <= 46 { true }
    else if book==&BibleBook::Leviticus && *chapter==27 && *verse <= 34 { true }
    else if book==&BibleBook::Numbers && *chapter==1 && *verse <= 54 { true }
    else if book==&BibleBook::Numbers && *chapter==2 && *verse <= 34 { true }
    else if book==&BibleBook::Numbers && *chapter==3 && *verse <= 51 { true }
    else if book==&BibleBook::Numbers && *chapter==4 && *verse <= 49 { true }
    else if book==&BibleBook::Numbers && *chapter==5 && *verse <= 31 { true }
    else if book==&BibleBook::Numbers && *chapter==6 && *verse <= 27 { true }
    else if book==&BibleBook::Numbers && *chapter==7 && *verse <= 89 { true }
    else if book==&BibleBook::Numbers && *chapter==8 && *verse <= 26 { true }
    else if book==&BibleBook::Numbers && *chapter==9 && *verse <= 23 { true }
    else if book==&BibleBook::Numbers && *chapter==10 && *verse <= 36 { true }
    else if book==&BibleBook::Numbers && *chapter==11 && *verse <= 35 { true }
    else if book==&BibleBook::Numbers && *chapter==12 && *verse <= 16 { true }
    else if book==&BibleBook::Numbers && *chapter==13 && *verse <= 33 { true }
    else if book==&BibleBook::Numbers && *chapter==14 && *verse <= 45 { true }
    else if book==&BibleBook::Numbers && *chapter==15 && *verse <= 41 { true }
    else if book==&BibleBook::Numbers && *chapter==16 && *verse <= 50 { true }
    else if book==&BibleBook::Numbers && *chapter==17 && *verse <= 13 { true }
    else if book==&BibleBook::Numbers && *chapter==18 && *verse <= 32 { true }
    else if book==&BibleBook::Numbers && *chapter==19 && *verse <= 22 { true }
    else if book==&BibleBook::Numbers && *chapter==20 && *verse <= 29 { true }
    else if book==&BibleBook::Numbers && *chapter==21 && *verse <= 35 { true }
    else if book==&BibleBook::Numbers && *chapter==22 && *verse <= 41 { true }
    else if book==&BibleBook::Numbers && *chapter==23 && *verse <= 30 { true }
    else if book==&BibleBook::Numbers && *chapter==24 && *verse <= 25 { true }
    else if book==&BibleBook::Numbers && *chapter==25 && *verse <= 18 { true }
    else if book==&BibleBook::Numbers && *chapter==26 && *verse <= 65 { true }
    else if book==&BibleBook::Numbers && *chapter==27 && *verse <= 23 { true }
    else if book==&BibleBook::Numbers && *chapter==28 && *verse <= 31 { true }
    else if book==&BibleBook::Numbers && *chapter==29 && *verse <= 40 { true }
    else if book==&BibleBook::Numbers && *chapter==30 && *verse <= 16 { true }
    else if book==&BibleBook::Numbers && *chapter==31 && *verse <= 54 { true }
    else if book==&BibleBook::Numbers && *chapter==32 && *verse <= 42 { true }
    else if book==&BibleBook::Numbers && *chapter==33 && *verse <= 56 { true }
    else if book==&BibleBook::Numbers && *chapter==34 && *verse <= 29 { true }
    else if book==&BibleBook::Numbers && *chapter==35 && *verse <= 34 { true }
    else if book==&BibleBook::Numbers && *chapter==36 && *verse <= 13 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==1 && *verse <= 46 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==2 && *verse <= 37 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==3 && *verse <= 29 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==4 && *verse <= 49 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==5 && *verse <= 33 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==6 && *verse <= 25 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==7 && *verse <= 26 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==8 && *verse <= 20 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==9 && *verse <= 29 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==10 && *verse <= 22 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==11 && *verse <= 32 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==12 && *verse <= 32 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==13 && *verse <= 18 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==14 && *verse <= 29 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==15 && *verse <= 23 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==16 && *verse <= 22 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==17 && *verse <= 20 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==18 && *verse <= 22 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==19 && *verse <= 21 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==20 && *verse <= 20 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==21 && *verse <= 23 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==22 && *verse <= 30 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==23 && *verse <= 25 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==24 && *verse <= 22 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==25 && *verse <= 19 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==26 && *verse <= 19 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==27 && *verse <= 26 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==28 && *verse <= 68 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==29 && *verse <= 29 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==30 && *verse <= 20 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==31 && *verse <= 30 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==32 && *verse <= 52 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==33 && *verse <= 29 { true }
    else if book==&BibleBook::Deuteronomy && *chapter==34 && *verse <= 12 { true }
    else if book==&BibleBook::Joshua && *chapter==1 && *verse <= 18 { true }
    else if book==&BibleBook::Joshua && *chapter==2 && *verse <= 24 { true }
    else if book==&BibleBook::Joshua && *chapter==3 && *verse <= 17 { true }
    else if book==&BibleBook::Joshua && *chapter==4 && *verse <= 24 { true }
    else if book==&BibleBook::Joshua && *chapter==5 && *verse <= 15 { true }
    else if book==&BibleBook::Joshua && *chapter==6 && *verse <= 27 { true }
    else if book==&BibleBook::Joshua && *chapter==7 && *verse <= 26 { true }
    else if book==&BibleBook::Joshua && *chapter==8 && *verse <= 35 { true }
    else if book==&BibleBook::Joshua && *chapter==9 && *verse <= 27 { true }
    else if book==&BibleBook::Joshua && *chapter==10 && *verse <= 43 { true }
    else if book==&BibleBook::Joshua && *chapter==11 && *verse <= 23 { true }
    else if book==&BibleBook::Joshua && *chapter==12 && *verse <= 24 { true }
    else if book==&BibleBook::Joshua && *chapter==13 && *verse <= 33 { true }
    else if book==&BibleBook::Joshua && *chapter==14 && *verse <= 15 { true }
    else if book==&BibleBook::Joshua && *chapter==15 && *verse <= 63 { true }
    else if book==&BibleBook::Joshua && *chapter==16 && *verse <= 10 { true }
    else if book==&BibleBook::Joshua && *chapter==17 && *verse <= 18 { true }
    else if book==&BibleBook::Joshua && *chapter==18 && *verse <= 28 { true }
    else if book==&BibleBook::Joshua && *chapter==19 && *verse <= 51 { true }
    else if book==&BibleBook::Joshua && *chapter==20 && *verse <= 9 { true }
    else if book==&BibleBook::Joshua && *chapter==21 && *verse <= 45 { true }
    else if book==&BibleBook::Joshua && *chapter==22 && *verse <= 34 { true }
    else if book==&BibleBook::Joshua && *chapter==23 && *verse <= 16 { true }
    else if book==&BibleBook::Joshua && *chapter==24 && *verse <= 33 { true }
    else if book==&BibleBook::Judges && *chapter==1 && *verse <= 36 { true }
    else if book==&BibleBook::Judges && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Judges && *chapter==3 && *verse <= 31 { true }
    else if book==&BibleBook::Judges && *chapter==4 && *verse <= 24 { true }
    else if book==&BibleBook::Judges && *chapter==5 && *verse <= 31 { true }
    else if book==&BibleBook::Judges && *chapter==6 && *verse <= 40 { true }
    else if book==&BibleBook::Judges && *chapter==7 && *verse <= 25 { true }
    else if book==&BibleBook::Judges && *chapter==8 && *verse <= 35 { true }
    else if book==&BibleBook::Judges && *chapter==9 && *verse <= 57 { true }
    else if book==&BibleBook::Judges && *chapter==10 && *verse <= 18 { true }
    else if book==&BibleBook::Judges && *chapter==11 && *verse <= 40 { true }
    else if book==&BibleBook::Judges && *chapter==12 && *verse <= 15 { true }
    else if book==&BibleBook::Judges && *chapter==13 && *verse <= 25 { true }
    else if book==&BibleBook::Judges && *chapter==14 && *verse <= 20 { true }
    else if book==&BibleBook::Judges && *chapter==15 && *verse <= 20 { true }
    else if book==&BibleBook::Judges && *chapter==16 && *verse <= 31 { true }
    else if book==&BibleBook::Judges && *chapter==17 && *verse <= 13 { true }
    else if book==&BibleBook::Judges && *chapter==18 && *verse <= 31 { true }
    else if book==&BibleBook::Judges && *chapter==19 && *verse <= 30 { true }
    else if book==&BibleBook::Judges && *chapter==20 && *verse <= 48 { true }
    else if book==&BibleBook::Judges && *chapter==21 && *verse <= 25 { true }
    else if book==&BibleBook::Ruth && *chapter==1 && *verse <= 22 { true }
    else if book==&BibleBook::Ruth && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Ruth && *chapter==3 && *verse <= 18 { true }
    else if book==&BibleBook::Ruth && *chapter==4 && *verse <= 22 { true }
    else if book==&BibleBook::ISamuel && *chapter==1 && *verse <= 28 { true }
    else if book==&BibleBook::ISamuel && *chapter==2 && *verse <= 36 { true }
    else if book==&BibleBook::ISamuel && *chapter==3 && *verse <= 21 { true }
    else if book==&BibleBook::ISamuel && *chapter==4 && *verse <= 22 { true }
    else if book==&BibleBook::ISamuel && *chapter==5 && *verse <= 12 { true }
    else if book==&BibleBook::ISamuel && *chapter==6 && *verse <= 21 { true }
    else if book==&BibleBook::ISamuel && *chapter==7 && *verse <= 17 { true }
    else if book==&BibleBook::ISamuel && *chapter==8 && *verse <= 22 { true }
    else if book==&BibleBook::ISamuel && *chapter==9 && *verse <= 27 { true }
    else if book==&BibleBook::ISamuel && *chapter==10 && *verse <= 27 { true }
    else if book==&BibleBook::ISamuel && *chapter==11 && *verse <= 15 { true }
    else if book==&BibleBook::ISamuel && *chapter==12 && *verse <= 25 { true }
    else if book==&BibleBook::ISamuel && *chapter==13 && *verse <= 23 { true }
    else if book==&BibleBook::ISamuel && *chapter==14 && *verse <= 52 { true }
    else if book==&BibleBook::ISamuel && *chapter==15 && *verse <= 35 { true }
    else if book==&BibleBook::ISamuel && *chapter==16 && *verse <= 23 { true }
    else if book==&BibleBook::ISamuel && *chapter==17 && *verse <= 58 { true }
    else if book==&BibleBook::ISamuel && *chapter==18 && *verse <= 30 { true }
    else if book==&BibleBook::ISamuel && *chapter==19 && *verse <= 24 { true }
    else if book==&BibleBook::ISamuel && *chapter==20 && *verse <= 42 { true }
    else if book==&BibleBook::ISamuel && *chapter==21 && *verse <= 15 { true }
    else if book==&BibleBook::ISamuel && *chapter==22 && *verse <= 23 { true }
    else if book==&BibleBook::ISamuel && *chapter==23 && *verse <= 29 { true }
    else if book==&BibleBook::ISamuel && *chapter==24 && *verse <= 22 { true }
    else if book==&BibleBook::ISamuel && *chapter==25 && *verse <= 44 { true }
    else if book==&BibleBook::ISamuel && *chapter==26 && *verse <= 25 { true }
    else if book==&BibleBook::ISamuel && *chapter==27 && *verse <= 12 { true }
    else if book==&BibleBook::ISamuel && *chapter==28 && *verse <= 25 { true }
    else if book==&BibleBook::ISamuel && *chapter==29 && *verse <= 11 { true }
    else if book==&BibleBook::ISamuel && *chapter==30 && *verse <= 31 { true }
    else if book==&BibleBook::ISamuel && *chapter==31 && *verse <= 13 { true }
    else if book==&BibleBook::IISamuel && *chapter==1 && *verse <= 27 { true }
    else if book==&BibleBook::IISamuel && *chapter==2 && *verse <= 32 { true }
    else if book==&BibleBook::IISamuel && *chapter==3 && *verse <= 39 { true }
    else if book==&BibleBook::IISamuel && *chapter==4 && *verse <= 12 { true }
    else if book==&BibleBook::IISamuel && *chapter==5 && *verse <= 25 { true }
    else if book==&BibleBook::IISamuel && *chapter==6 && *verse <= 23 { true }
    else if book==&BibleBook::IISamuel && *chapter==7 && *verse <= 29 { true }
    else if book==&BibleBook::IISamuel && *chapter==8 && *verse <= 18 { true }
    else if book==&BibleBook::IISamuel && *chapter==9 && *verse <= 13 { true }
    else if book==&BibleBook::IISamuel && *chapter==10 && *verse <= 19 { true }
    else if book==&BibleBook::IISamuel && *chapter==11 && *verse <= 27 { true }
    else if book==&BibleBook::IISamuel && *chapter==12 && *verse <= 31 { true }
    else if book==&BibleBook::IISamuel && *chapter==13 && *verse <= 39 { true }
    else if book==&BibleBook::IISamuel && *chapter==14 && *verse <= 33 { true }
    else if book==&BibleBook::IISamuel && *chapter==15 && *verse <= 37 { true }
    else if book==&BibleBook::IISamuel && *chapter==16 && *verse <= 23 { true }
    else if book==&BibleBook::IISamuel && *chapter==17 && *verse <= 29 { true }
    else if book==&BibleBook::IISamuel && *chapter==18 && *verse <= 33 { true }
    else if book==&BibleBook::IISamuel && *chapter==19 && *verse <= 43 { true }
    else if book==&BibleBook::IISamuel && *chapter==20 && *verse <= 26 { true }
    else if book==&BibleBook::IISamuel && *chapter==21 && *verse <= 22 { true }
    else if book==&BibleBook::IISamuel && *chapter==22 && *verse <= 51 { true }
    else if book==&BibleBook::IISamuel && *chapter==23 && *verse <= 39 { true }
    else if book==&BibleBook::IISamuel && *chapter==24 && *verse <= 25 { true }
    else if book==&BibleBook::IKings && *chapter==1 && *verse <= 53 { true }
    else if book==&BibleBook::IKings && *chapter==2 && *verse <= 46 { true }
    else if book==&BibleBook::IKings && *chapter==3 && *verse <= 28 { true }
    else if book==&BibleBook::IKings && *chapter==4 && *verse <= 34 { true }
    else if book==&BibleBook::IKings && *chapter==5 && *verse <= 18 { true }
    else if book==&BibleBook::IKings && *chapter==6 && *verse <= 38 { true }
    else if book==&BibleBook::IKings && *chapter==7 && *verse <= 51 { true }
    else if book==&BibleBook::IKings && *chapter==8 && *verse <= 66 { true }
    else if book==&BibleBook::IKings && *chapter==9 && *verse <= 28 { true }
    else if book==&BibleBook::IKings && *chapter==10 && *verse <= 29 { true }
    else if book==&BibleBook::IKings && *chapter==11 && *verse <= 43 { true }
    else if book==&BibleBook::IKings && *chapter==12 && *verse <= 33 { true }
    else if book==&BibleBook::IKings && *chapter==13 && *verse <= 34 { true }
    else if book==&BibleBook::IKings && *chapter==14 && *verse <= 31 { true }
    else if book==&BibleBook::IKings && *chapter==15 && *verse <= 34 { true }
    else if book==&BibleBook::IKings && *chapter==16 && *verse <= 34 { true }
    else if book==&BibleBook::IKings && *chapter==17 && *verse <= 24 { true }
    else if book==&BibleBook::IKings && *chapter==18 && *verse <= 46 { true }
    else if book==&BibleBook::IKings && *chapter==19 && *verse <= 21 { true }
    else if book==&BibleBook::IKings && *chapter==20 && *verse <= 43 { true }
    else if book==&BibleBook::IKings && *chapter==21 && *verse <= 29 { true }
    else if book==&BibleBook::IKings && *chapter==22 && *verse <= 53 { true }
    else if book==&BibleBook::IIKings && *chapter==1 && *verse <= 18 { true }
    else if book==&BibleBook::IIKings && *chapter==2 && *verse <= 25 { true }
    else if book==&BibleBook::IIKings && *chapter==3 && *verse <= 27 { true }
    else if book==&BibleBook::IIKings && *chapter==4 && *verse <= 44 { true }
    else if book==&BibleBook::IIKings && *chapter==5 && *verse <= 27 { true }
    else if book==&BibleBook::IIKings && *chapter==6 && *verse <= 33 { true }
    else if book==&BibleBook::IIKings && *chapter==7 && *verse <= 20 { true }
    else if book==&BibleBook::IIKings && *chapter==8 && *verse <= 29 { true }
    else if book==&BibleBook::IIKings && *chapter==9 && *verse <= 37 { true }
    else if book==&BibleBook::IIKings && *chapter==10 && *verse <= 36 { true }
    else if book==&BibleBook::IIKings && *chapter==11 && *verse <= 21 { true }
    else if book==&BibleBook::IIKings && *chapter==12 && *verse <= 21 { true }
    else if book==&BibleBook::IIKings && *chapter==13 && *verse <= 25 { true }
    else if book==&BibleBook::IIKings && *chapter==14 && *verse <= 29 { true }
    else if book==&BibleBook::IIKings && *chapter==15 && *verse <= 38 { true }
    else if book==&BibleBook::IIKings && *chapter==16 && *verse <= 20 { true }
    else if book==&BibleBook::IIKings && *chapter==17 && *verse <= 41 { true }
    else if book==&BibleBook::IIKings && *chapter==18 && *verse <= 37 { true }
    else if book==&BibleBook::IIKings && *chapter==19 && *verse <= 37 { true }
    else if book==&BibleBook::IIKings && *chapter==20 && *verse <= 21 { true }
    else if book==&BibleBook::IIKings && *chapter==21 && *verse <= 26 { true }
    else if book==&BibleBook::IIKings && *chapter==22 && *verse <= 20 { true }
    else if book==&BibleBook::IIKings && *chapter==23 && *verse <= 37 { true }
    else if book==&BibleBook::IIKings && *chapter==24 && *verse <= 20 { true }
    else if book==&BibleBook::IIKings && *chapter==25 && *verse <= 30 { true }
    else if book==&BibleBook::IChronicles && *chapter==1 && *verse <= 54 { true }
    else if book==&BibleBook::IChronicles && *chapter==2 && *verse <= 55 { true }
    else if book==&BibleBook::IChronicles && *chapter==3 && *verse <= 24 { true }
    else if book==&BibleBook::IChronicles && *chapter==4 && *verse <= 43 { true }
    else if book==&BibleBook::IChronicles && *chapter==5 && *verse <= 26 { true }
    else if book==&BibleBook::IChronicles && *chapter==6 && *verse <= 81 { true }
    else if book==&BibleBook::IChronicles && *chapter==7 && *verse <= 40 { true }
    else if book==&BibleBook::IChronicles && *chapter==8 && *verse <= 40 { true }
    else if book==&BibleBook::IChronicles && *chapter==9 && *verse <= 44 { true }
    else if book==&BibleBook::IChronicles && *chapter==10 && *verse <= 14 { true }
    else if book==&BibleBook::IChronicles && *chapter==11 && *verse <= 47 { true }
    else if book==&BibleBook::IChronicles && *chapter==12 && *verse <= 40 { true }
    else if book==&BibleBook::IChronicles && *chapter==13 && *verse <= 14 { true }
    else if book==&BibleBook::IChronicles && *chapter==14 && *verse <= 17 { true }
    else if book==&BibleBook::IChronicles && *chapter==15 && *verse <= 29 { true }
    else if book==&BibleBook::IChronicles && *chapter==16 && *verse <= 43 { true }
    else if book==&BibleBook::IChronicles && *chapter==17 && *verse <= 27 { true }
    else if book==&BibleBook::IChronicles && *chapter==18 && *verse <= 17 { true }
    else if book==&BibleBook::IChronicles && *chapter==19 && *verse <= 19 { true }
    else if book==&BibleBook::IChronicles && *chapter==20 && *verse <= 8 { true }
    else if book==&BibleBook::IChronicles && *chapter==21 && *verse <= 30 { true }
    else if book==&BibleBook::IChronicles && *chapter==22 && *verse <= 19 { true }
    else if book==&BibleBook::IChronicles && *chapter==23 && *verse <= 32 { true }
    else if book==&BibleBook::IChronicles && *chapter==24 && *verse <= 31 { true }
    else if book==&BibleBook::IChronicles && *chapter==25 && *verse <= 31 { true }
    else if book==&BibleBook::IChronicles && *chapter==26 && *verse <= 32 { true }
    else if book==&BibleBook::IChronicles && *chapter==27 && *verse <= 34 { true }
    else if book==&BibleBook::IChronicles && *chapter==28 && *verse <= 21 { true }
    else if book==&BibleBook::IChronicles && *chapter==29 && *verse <= 30 { true }
    else if book==&BibleBook::IIChronicles && *chapter==1 && *verse <= 17 { true }
    else if book==&BibleBook::IIChronicles && *chapter==2 && *verse <= 18 { true }
    else if book==&BibleBook::IIChronicles && *chapter==3 && *verse <= 17 { true }
    else if book==&BibleBook::IIChronicles && *chapter==4 && *verse <= 22 { true }
    else if book==&BibleBook::IIChronicles && *chapter==5 && *verse <= 14 { true }
    else if book==&BibleBook::IIChronicles && *chapter==6 && *verse <= 42 { true }
    else if book==&BibleBook::IIChronicles && *chapter==7 && *verse <= 22 { true }
    else if book==&BibleBook::IIChronicles && *chapter==8 && *verse <= 18 { true }
    else if book==&BibleBook::IIChronicles && *chapter==9 && *verse <= 31 { true }
    else if book==&BibleBook::IIChronicles && *chapter==10 && *verse <= 19 { true }
    else if book==&BibleBook::IIChronicles && *chapter==11 && *verse <= 23 { true }
    else if book==&BibleBook::IIChronicles && *chapter==12 && *verse <= 16 { true }
    else if book==&BibleBook::IIChronicles && *chapter==13 && *verse <= 22 { true }
    else if book==&BibleBook::IIChronicles && *chapter==14 && *verse <= 15 { true }
    else if book==&BibleBook::IIChronicles && *chapter==15 && *verse <= 19 { true }
    else if book==&BibleBook::IIChronicles && *chapter==16 && *verse <= 14 { true }
    else if book==&BibleBook::IIChronicles && *chapter==17 && *verse <= 19 { true }
    else if book==&BibleBook::IIChronicles && *chapter==18 && *verse <= 34 { true }
    else if book==&BibleBook::IIChronicles && *chapter==19 && *verse <= 11 { true }
    else if book==&BibleBook::IIChronicles && *chapter==20 && *verse <= 37 { true }
    else if book==&BibleBook::IIChronicles && *chapter==21 && *verse <= 20 { true }
    else if book==&BibleBook::IIChronicles && *chapter==22 && *verse <= 12 { true }
    else if book==&BibleBook::IIChronicles && *chapter==23 && *verse <= 21 { true }
    else if book==&BibleBook::IIChronicles && *chapter==24 && *verse <= 27 { true }
    else if book==&BibleBook::IIChronicles && *chapter==25 && *verse <= 28 { true }
    else if book==&BibleBook::IIChronicles && *chapter==26 && *verse <= 23 { true }
    else if book==&BibleBook::IIChronicles && *chapter==27 && *verse <= 9 { true }
    else if book==&BibleBook::IIChronicles && *chapter==28 && *verse <= 27 { true }
    else if book==&BibleBook::IIChronicles && *chapter==29 && *verse <= 36 { true }
    else if book==&BibleBook::IIChronicles && *chapter==30 && *verse <= 27 { true }
    else if book==&BibleBook::IIChronicles && *chapter==31 && *verse <= 21 { true }
    else if book==&BibleBook::IIChronicles && *chapter==32 && *verse <= 33 { true }
    else if book==&BibleBook::IIChronicles && *chapter==33 && *verse <= 25 { true }
    else if book==&BibleBook::IIChronicles && *chapter==34 && *verse <= 33 { true }
    else if book==&BibleBook::IIChronicles && *chapter==35 && *verse <= 27 { true }
    else if book==&BibleBook::IIChronicles && *chapter==36 && *verse <= 23 { true }
    else if book==&BibleBook::Ezra && *chapter==1 && *verse <= 11 { true }
    else if book==&BibleBook::Ezra && *chapter==2 && *verse <= 70 { true }
    else if book==&BibleBook::Ezra && *chapter==3 && *verse <= 13 { true }
    else if book==&BibleBook::Ezra && *chapter==4 && *verse <= 24 { true }
    else if book==&BibleBook::Ezra && *chapter==5 && *verse <= 17 { true }
    else if book==&BibleBook::Ezra && *chapter==6 && *verse <= 22 { true }
    else if book==&BibleBook::Ezra && *chapter==7 && *verse <= 28 { true }
    else if book==&BibleBook::Ezra && *chapter==8 && *verse <= 36 { true }
    else if book==&BibleBook::Ezra && *chapter==9 && *verse <= 15 { true }
    else if book==&BibleBook::Ezra && *chapter==10 && *verse <= 44 { true }
    else if book==&BibleBook::Nehemiah && *chapter==1 && *verse <= 11 { true }
    else if book==&BibleBook::Nehemiah && *chapter==2 && *verse <= 20 { true }
    else if book==&BibleBook::Nehemiah && *chapter==3 && *verse <= 32 { true }
    else if book==&BibleBook::Nehemiah && *chapter==4 && *verse <= 23 { true }
    else if book==&BibleBook::Nehemiah && *chapter==5 && *verse <= 19 { true }
    else if book==&BibleBook::Nehemiah && *chapter==6 && *verse <= 19 { true }
    else if book==&BibleBook::Nehemiah && *chapter==7 && *verse <= 73 { true }
    else if book==&BibleBook::Nehemiah && *chapter==8 && *verse <= 18 { true }
    else if book==&BibleBook::Nehemiah && *chapter==9 && *verse <= 38 { true }
    else if book==&BibleBook::Nehemiah && *chapter==10 && *verse <= 39 { true }
    else if book==&BibleBook::Nehemiah && *chapter==11 && *verse <= 36 { true }
    else if book==&BibleBook::Nehemiah && *chapter==12 && *verse <= 47 { true }
    else if book==&BibleBook::Nehemiah && *chapter==13 && *verse <= 31 { true }
    else if book==&BibleBook::Esther && *chapter==1 && *verse <= 22 { true }
    else if book==&BibleBook::Esther && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Esther && *chapter==3 && *verse <= 15 { true }
    else if book==&BibleBook::Esther && *chapter==4 && *verse <= 17 { true }
    else if book==&BibleBook::Esther && *chapter==5 && *verse <= 14 { true }
    else if book==&BibleBook::Esther && *chapter==6 && *verse <= 14 { true }
    else if book==&BibleBook::Esther && *chapter==7 && *verse <= 10 { true }
    else if book==&BibleBook::Esther && *chapter==8 && *verse <= 17 { true }
    else if book==&BibleBook::Esther && *chapter==9 && *verse <= 32 { true }
    else if book==&BibleBook::Esther && *chapter==10 && *verse <= 3 { true }
    else if book==&BibleBook::Job && *chapter==1 && *verse <= 22 { true }
    else if book==&BibleBook::Job && *chapter==2 && *verse <= 13 { true }
    else if book==&BibleBook::Job && *chapter==3 && *verse <= 26 { true }
    else if book==&BibleBook::Job && *chapter==4 && *verse <= 21 { true }
    else if book==&BibleBook::Job && *chapter==5 && *verse <= 27 { true }
    else if book==&BibleBook::Job && *chapter==6 && *verse <= 30 { true }
    else if book==&BibleBook::Job && *chapter==7 && *verse <= 21 { true }
    else if book==&BibleBook::Job && *chapter==8 && *verse <= 22 { true }
    else if book==&BibleBook::Job && *chapter==9 && *verse <= 35 { true }
    else if book==&BibleBook::Job && *chapter==10 && *verse <= 22 { true }
    else if book==&BibleBook::Job && *chapter==11 && *verse <= 20 { true }
    else if book==&BibleBook::Job && *chapter==12 && *verse <= 25 { true }
    else if book==&BibleBook::Job && *chapter==13 && *verse <= 28 { true }
    else if book==&BibleBook::Job && *chapter==14 && *verse <= 22 { true }
    else if book==&BibleBook::Job && *chapter==15 && *verse <= 35 { true }
    else if book==&BibleBook::Job && *chapter==16 && *verse <= 22 { true }
    else if book==&BibleBook::Job && *chapter==17 && *verse <= 16 { true }
    else if book==&BibleBook::Job && *chapter==18 && *verse <= 21 { true }
    else if book==&BibleBook::Job && *chapter==19 && *verse <= 29 { true }
    else if book==&BibleBook::Job && *chapter==20 && *verse <= 29 { true }
    else if book==&BibleBook::Job && *chapter==21 && *verse <= 34 { true }
    else if book==&BibleBook::Job && *chapter==22 && *verse <= 30 { true }
    else if book==&BibleBook::Job && *chapter==23 && *verse <= 17 { true }
    else if book==&BibleBook::Job && *chapter==24 && *verse <= 25 { true }
    else if book==&BibleBook::Job && *chapter==25 && *verse <= 6 { true }
    else if book==&BibleBook::Job && *chapter==26 && *verse <= 14 { true }
    else if book==&BibleBook::Job && *chapter==27 && *verse <= 23 { true }
    else if book==&BibleBook::Job && *chapter==28 && *verse <= 28 { true }
    else if book==&BibleBook::Job && *chapter==29 && *verse <= 25 { true }
    else if book==&BibleBook::Job && *chapter==30 && *verse <= 31 { true }
    else if book==&BibleBook::Job && *chapter==31 && *verse <= 40 { true }
    else if book==&BibleBook::Job && *chapter==32 && *verse <= 22 { true }
    else if book==&BibleBook::Job && *chapter==33 && *verse <= 33 { true }
    else if book==&BibleBook::Job && *chapter==34 && *verse <= 37 { true }
    else if book==&BibleBook::Job && *chapter==35 && *verse <= 16 { true }
    else if book==&BibleBook::Job && *chapter==36 && *verse <= 33 { true }
    else if book==&BibleBook::Job && *chapter==37 && *verse <= 24 { true }
    else if book==&BibleBook::Job && *chapter==38 && *verse <= 41 { true }
    else if book==&BibleBook::Job && *chapter==39 && *verse <= 30 { true }
    else if book==&BibleBook::Job && *chapter==40 && *verse <= 24 { true }
    else if book==&BibleBook::Job && *chapter==41 && *verse <= 34 { true }
    else if book==&BibleBook::Job && *chapter==42 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==1 && *verse <= 6 { true }
    else if book==&BibleBook::Psalm && *chapter==2 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==3 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==4 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==5 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==6 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==7 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==8 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==9 && *verse <= 20 { true }
    else if book==&BibleBook::Psalm && *chapter==10 && *verse <= 18 { true }
    else if book==&BibleBook::Psalm && *chapter==11 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==12 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==13 && *verse <= 6 { true }
    else if book==&BibleBook::Psalm && *chapter==14 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==15 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==16 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==17 && *verse <= 15 { true }
    else if book==&BibleBook::Psalm && *chapter==18 && *verse <= 50 { true }
    else if book==&BibleBook::Psalm && *chapter==19 && *verse <= 14 { true }
    else if book==&BibleBook::Psalm && *chapter==20 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==21 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==22 && *verse <= 31 { true }
    else if book==&BibleBook::Psalm && *chapter==23 && *verse <= 6 { true }
    else if book==&BibleBook::Psalm && *chapter==24 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==25 && *verse <= 22 { true }
    else if book==&BibleBook::Psalm && *chapter==26 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==27 && *verse <= 14 { true }
    else if book==&BibleBook::Psalm && *chapter==28 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==29 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==30 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==31 && *verse <= 24 { true }
    else if book==&BibleBook::Psalm && *chapter==32 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==33 && *verse <= 22 { true }
    else if book==&BibleBook::Psalm && *chapter==34 && *verse <= 22 { true }
    else if book==&BibleBook::Psalm && *chapter==35 && *verse <= 28 { true }
    else if book==&BibleBook::Psalm && *chapter==36 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==37 && *verse <= 40 { true }
    else if book==&BibleBook::Psalm && *chapter==38 && *verse <= 22 { true }
    else if book==&BibleBook::Psalm && *chapter==39 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==40 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==41 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==42 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==43 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==44 && *verse <= 26 { true }
    else if book==&BibleBook::Psalm && *chapter==45 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==46 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==47 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==48 && *verse <= 14 { true }
    else if book==&BibleBook::Psalm && *chapter==49 && *verse <= 20 { true }
    else if book==&BibleBook::Psalm && *chapter==50 && *verse <= 23 { true }
    else if book==&BibleBook::Psalm && *chapter==51 && *verse <= 19 { true }
    else if book==&BibleBook::Psalm && *chapter==52 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==53 && *verse <= 6 { true }
    else if book==&BibleBook::Psalm && *chapter==54 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==55 && *verse <= 23 { true }
    else if book==&BibleBook::Psalm && *chapter==56 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==57 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==58 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==59 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==60 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==61 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==62 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==63 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==64 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==65 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==66 && *verse <= 20 { true }
    else if book==&BibleBook::Psalm && *chapter==67 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==68 && *verse <= 35 { true }
    else if book==&BibleBook::Psalm && *chapter==69 && *verse <= 36 { true }
    else if book==&BibleBook::Psalm && *chapter==70 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==71 && *verse <= 24 { true }
    else if book==&BibleBook::Psalm && *chapter==72 && *verse <= 20 { true }
    else if book==&BibleBook::Psalm && *chapter==73 && *verse <= 28 { true }
    else if book==&BibleBook::Psalm && *chapter==74 && *verse <= 23 { true }
    else if book==&BibleBook::Psalm && *chapter==75 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==76 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==77 && *verse <= 20 { true }
    else if book==&BibleBook::Psalm && *chapter==78 && *verse <= 72 { true }
    else if book==&BibleBook::Psalm && *chapter==79 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==80 && *verse <= 19 { true }
    else if book==&BibleBook::Psalm && *chapter==81 && *verse <= 16 { true }
    else if book==&BibleBook::Psalm && *chapter==82 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==83 && *verse <= 18 { true }
    else if book==&BibleBook::Psalm && *chapter==84 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==85 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==86 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==87 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==88 && *verse <= 18 { true }
    else if book==&BibleBook::Psalm && *chapter==89 && *verse <= 52 { true }
    else if book==&BibleBook::Psalm && *chapter==90 && *verse <= 17 { true }
    else if book==&BibleBook::Psalm && *chapter==91 && *verse <= 16 { true }
    else if book==&BibleBook::Psalm && *chapter==92 && *verse <= 15 { true }
    else if book==&BibleBook::Psalm && *chapter==93 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==94 && *verse <= 23 { true }
    else if book==&BibleBook::Psalm && *chapter==95 && *verse <= 11 { true }
    else if book==&BibleBook::Psalm && *chapter==96 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==97 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==98 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==99 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==100 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==101 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==102 && *verse <= 28 { true }
    else if book==&BibleBook::Psalm && *chapter==103 && *verse <= 22 { true }
    else if book==&BibleBook::Psalm && *chapter==104 && *verse <= 35 { true }
    else if book==&BibleBook::Psalm && *chapter==105 && *verse <= 45 { true }
    else if book==&BibleBook::Psalm && *chapter==106 && *verse <= 48 { true }
    else if book==&BibleBook::Psalm && *chapter==107 && *verse <= 43 { true }
    else if book==&BibleBook::Psalm && *chapter==108 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==109 && *verse <= 31 { true }
    else if book==&BibleBook::Psalm && *chapter==110 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==111 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==112 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==113 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==114 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==115 && *verse <= 18 { true }
    else if book==&BibleBook::Psalm && *chapter==116 && *verse <= 19 { true }
    else if book==&BibleBook::Psalm && *chapter==117 && *verse <= 2 { true }
    else if book==&BibleBook::Psalm && *chapter==118 && *verse <= 29 { true }
    else if book==&BibleBook::Psalm && *chapter==119 && *verse <= 176 { true }
    else if book==&BibleBook::Psalm && *chapter==120 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==121 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==122 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==123 && *verse <= 4 { true }
    else if book==&BibleBook::Psalm && *chapter==124 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==125 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==126 && *verse <= 6 { true }
    else if book==&BibleBook::Psalm && *chapter==127 && *verse <= 5 { true }
    else if book==&BibleBook::Psalm && *chapter==128 && *verse <= 6 { true }
    else if book==&BibleBook::Psalm && *chapter==129 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==130 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==131 && *verse <= 3 { true }
    else if book==&BibleBook::Psalm && *chapter==132 && *verse <= 18 { true }
    else if book==&BibleBook::Psalm && *chapter==133 && *verse <= 3 { true }
    else if book==&BibleBook::Psalm && *chapter==134 && *verse <= 3 { true }
    else if book==&BibleBook::Psalm && *chapter==135 && *verse <= 21 { true }
    else if book==&BibleBook::Psalm && *chapter==136 && *verse <= 26 { true }
    else if book==&BibleBook::Psalm && *chapter==137 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==138 && *verse <= 8 { true }
    else if book==&BibleBook::Psalm && *chapter==139 && *verse <= 24 { true }
    else if book==&BibleBook::Psalm && *chapter==140 && *verse <= 13 { true }
    else if book==&BibleBook::Psalm && *chapter==141 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==142 && *verse <= 7 { true }
    else if book==&BibleBook::Psalm && *chapter==143 && *verse <= 12 { true }
    else if book==&BibleBook::Psalm && *chapter==144 && *verse <= 15 { true }
    else if book==&BibleBook::Psalm && *chapter==145 && *verse <= 21 { true }
    else if book==&BibleBook::Psalm && *chapter==146 && *verse <= 10 { true }
    else if book==&BibleBook::Psalm && *chapter==147 && *verse <= 20 { true }
    else if book==&BibleBook::Psalm && *chapter==148 && *verse <= 14 { true }
    else if book==&BibleBook::Psalm && *chapter==149 && *verse <= 9 { true }
    else if book==&BibleBook::Psalm && *chapter==150 && *verse <= 6 { true }
    else if book==&BibleBook::Proverbs && *chapter==1 && *verse <= 33 { true }
    else if book==&BibleBook::Proverbs && *chapter==2 && *verse <= 22 { true }
    else if book==&BibleBook::Proverbs && *chapter==3 && *verse <= 35 { true }
    else if book==&BibleBook::Proverbs && *chapter==4 && *verse <= 27 { true }
    else if book==&BibleBook::Proverbs && *chapter==5 && *verse <= 23 { true }
    else if book==&BibleBook::Proverbs && *chapter==6 && *verse <= 35 { true }
    else if book==&BibleBook::Proverbs && *chapter==7 && *verse <= 27 { true }
    else if book==&BibleBook::Proverbs && *chapter==8 && *verse <= 36 { true }
    else if book==&BibleBook::Proverbs && *chapter==9 && *verse <= 18 { true }
    else if book==&BibleBook::Proverbs && *chapter==10 && *verse <= 32 { true }
    else if book==&BibleBook::Proverbs && *chapter==11 && *verse <= 31 { true }
    else if book==&BibleBook::Proverbs && *chapter==12 && *verse <= 28 { true }
    else if book==&BibleBook::Proverbs && *chapter==13 && *verse <= 25 { true }
    else if book==&BibleBook::Proverbs && *chapter==14 && *verse <= 35 { true }
    else if book==&BibleBook::Proverbs && *chapter==15 && *verse <= 33 { true }
    else if book==&BibleBook::Proverbs && *chapter==16 && *verse <= 33 { true }
    else if book==&BibleBook::Proverbs && *chapter==17 && *verse <= 28 { true }
    else if book==&BibleBook::Proverbs && *chapter==18 && *verse <= 24 { true }
    else if book==&BibleBook::Proverbs && *chapter==19 && *verse <= 29 { true }
    else if book==&BibleBook::Proverbs && *chapter==20 && *verse <= 30 { true }
    else if book==&BibleBook::Proverbs && *chapter==21 && *verse <= 31 { true }
    else if book==&BibleBook::Proverbs && *chapter==22 && *verse <= 29 { true }
    else if book==&BibleBook::Proverbs && *chapter==23 && *verse <= 35 { true }
    else if book==&BibleBook::Proverbs && *chapter==24 && *verse <= 34 { true }
    else if book==&BibleBook::Proverbs && *chapter==25 && *verse <= 28 { true }
    else if book==&BibleBook::Proverbs && *chapter==26 && *verse <= 28 { true }
    else if book==&BibleBook::Proverbs && *chapter==27 && *verse <= 27 { true }
    else if book==&BibleBook::Proverbs && *chapter==28 && *verse <= 28 { true }
    else if book==&BibleBook::Proverbs && *chapter==29 && *verse <= 27 { true }
    else if book==&BibleBook::Proverbs && *chapter==30 && *verse <= 33 { true }
    else if book==&BibleBook::Proverbs && *chapter==31 && *verse <= 31 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==1 && *verse <= 18 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==2 && *verse <= 26 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==3 && *verse <= 22 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==4 && *verse <= 16 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==5 && *verse <= 20 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==6 && *verse <= 12 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==7 && *verse <= 29 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==8 && *verse <= 17 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==9 && *verse <= 18 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==10 && *verse <= 20 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==11 && *verse <= 10 { true }
    else if book==&BibleBook::Ecclesiastes && *chapter==12 && *verse <= 14 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==1 && *verse <= 17 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==2 && *verse <= 17 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==3 && *verse <= 11 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==4 && *verse <= 16 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==5 && *verse <= 16 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==6 && *verse <= 13 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==7 && *verse <= 13 { true }
    else if book==&BibleBook::SongofSolomon && *chapter==8 && *verse <= 14 { true }
    else if book==&BibleBook::Isaiah && *chapter==1 && *verse <= 31 { true }
    else if book==&BibleBook::Isaiah && *chapter==2 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==3 && *verse <= 26 { true }
    else if book==&BibleBook::Isaiah && *chapter==4 && *verse <= 6 { true }
    else if book==&BibleBook::Isaiah && *chapter==5 && *verse <= 30 { true }
    else if book==&BibleBook::Isaiah && *chapter==6 && *verse <= 13 { true }
    else if book==&BibleBook::Isaiah && *chapter==7 && *verse <= 25 { true }
    else if book==&BibleBook::Isaiah && *chapter==8 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==9 && *verse <= 21 { true }
    else if book==&BibleBook::Isaiah && *chapter==10 && *verse <= 34 { true }
    else if book==&BibleBook::Isaiah && *chapter==11 && *verse <= 16 { true }
    else if book==&BibleBook::Isaiah && *chapter==12 && *verse <= 6 { true }
    else if book==&BibleBook::Isaiah && *chapter==13 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==14 && *verse <= 32 { true }
    else if book==&BibleBook::Isaiah && *chapter==15 && *verse <= 9 { true }
    else if book==&BibleBook::Isaiah && *chapter==16 && *verse <= 14 { true }
    else if book==&BibleBook::Isaiah && *chapter==17 && *verse <= 14 { true }
    else if book==&BibleBook::Isaiah && *chapter==18 && *verse <= 7 { true }
    else if book==&BibleBook::Isaiah && *chapter==19 && *verse <= 25 { true }
    else if book==&BibleBook::Isaiah && *chapter==20 && *verse <= 6 { true }
    else if book==&BibleBook::Isaiah && *chapter==21 && *verse <= 17 { true }
    else if book==&BibleBook::Isaiah && *chapter==22 && *verse <= 25 { true }
    else if book==&BibleBook::Isaiah && *chapter==23 && *verse <= 18 { true }
    else if book==&BibleBook::Isaiah && *chapter==24 && *verse <= 23 { true }
    else if book==&BibleBook::Isaiah && *chapter==25 && *verse <= 12 { true }
    else if book==&BibleBook::Isaiah && *chapter==26 && *verse <= 21 { true }
    else if book==&BibleBook::Isaiah && *chapter==27 && *verse <= 13 { true }
    else if book==&BibleBook::Isaiah && *chapter==28 && *verse <= 29 { true }
    else if book==&BibleBook::Isaiah && *chapter==29 && *verse <= 24 { true }
    else if book==&BibleBook::Isaiah && *chapter==30 && *verse <= 33 { true }
    else if book==&BibleBook::Isaiah && *chapter==31 && *verse <= 9 { true }
    else if book==&BibleBook::Isaiah && *chapter==32 && *verse <= 20 { true }
    else if book==&BibleBook::Isaiah && *chapter==33 && *verse <= 24 { true }
    else if book==&BibleBook::Isaiah && *chapter==34 && *verse <= 17 { true }
    else if book==&BibleBook::Isaiah && *chapter==35 && *verse <= 10 { true }
    else if book==&BibleBook::Isaiah && *chapter==36 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==37 && *verse <= 38 { true }
    else if book==&BibleBook::Isaiah && *chapter==38 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==39 && *verse <= 8 { true }
    else if book==&BibleBook::Isaiah && *chapter==40 && *verse <= 31 { true }
    else if book==&BibleBook::Isaiah && *chapter==41 && *verse <= 29 { true }
    else if book==&BibleBook::Isaiah && *chapter==42 && *verse <= 25 { true }
    else if book==&BibleBook::Isaiah && *chapter==43 && *verse <= 28 { true }
    else if book==&BibleBook::Isaiah && *chapter==44 && *verse <= 28 { true }
    else if book==&BibleBook::Isaiah && *chapter==45 && *verse <= 25 { true }
    else if book==&BibleBook::Isaiah && *chapter==46 && *verse <= 13 { true }
    else if book==&BibleBook::Isaiah && *chapter==47 && *verse <= 15 { true }
    else if book==&BibleBook::Isaiah && *chapter==48 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==49 && *verse <= 26 { true }
    else if book==&BibleBook::Isaiah && *chapter==50 && *verse <= 11 { true }
    else if book==&BibleBook::Isaiah && *chapter==51 && *verse <= 23 { true }
    else if book==&BibleBook::Isaiah && *chapter==52 && *verse <= 15 { true }
    else if book==&BibleBook::Isaiah && *chapter==53 && *verse <= 12 { true }
    else if book==&BibleBook::Isaiah && *chapter==54 && *verse <= 17 { true }
    else if book==&BibleBook::Isaiah && *chapter==55 && *verse <= 13 { true }
    else if book==&BibleBook::Isaiah && *chapter==56 && *verse <= 12 { true }
    else if book==&BibleBook::Isaiah && *chapter==57 && *verse <= 21 { true }
    else if book==&BibleBook::Isaiah && *chapter==58 && *verse <= 14 { true }
    else if book==&BibleBook::Isaiah && *chapter==59 && *verse <= 21 { true }
    else if book==&BibleBook::Isaiah && *chapter==60 && *verse <= 22 { true }
    else if book==&BibleBook::Isaiah && *chapter==61 && *verse <= 11 { true }
    else if book==&BibleBook::Isaiah && *chapter==62 && *verse <= 12 { true }
    else if book==&BibleBook::Isaiah && *chapter==63 && *verse <= 19 { true }
    else if book==&BibleBook::Isaiah && *chapter==64 && *verse <= 12 { true }
    else if book==&BibleBook::Isaiah && *chapter==65 && *verse <= 25 { true }
    else if book==&BibleBook::Isaiah && *chapter==66 && *verse <= 24 { true }
    else if book==&BibleBook::Jeremiah && *chapter==1 && *verse <= 19 { true }
    else if book==&BibleBook::Jeremiah && *chapter==2 && *verse <= 37 { true }
    else if book==&BibleBook::Jeremiah && *chapter==3 && *verse <= 25 { true }
    else if book==&BibleBook::Jeremiah && *chapter==4 && *verse <= 31 { true }
    else if book==&BibleBook::Jeremiah && *chapter==5 && *verse <= 31 { true }
    else if book==&BibleBook::Jeremiah && *chapter==6 && *verse <= 30 { true }
    else if book==&BibleBook::Jeremiah && *chapter==7 && *verse <= 34 { true }
    else if book==&BibleBook::Jeremiah && *chapter==8 && *verse <= 22 { true }
    else if book==&BibleBook::Jeremiah && *chapter==9 && *verse <= 26 { true }
    else if book==&BibleBook::Jeremiah && *chapter==10 && *verse <= 25 { true }
    else if book==&BibleBook::Jeremiah && *chapter==11 && *verse <= 23 { true }
    else if book==&BibleBook::Jeremiah && *chapter==12 && *verse <= 17 { true }
    else if book==&BibleBook::Jeremiah && *chapter==13 && *verse <= 27 { true }
    else if book==&BibleBook::Jeremiah && *chapter==14 && *verse <= 22 { true }
    else if book==&BibleBook::Jeremiah && *chapter==15 && *verse <= 21 { true }
    else if book==&BibleBook::Jeremiah && *chapter==16 && *verse <= 21 { true }
    else if book==&BibleBook::Jeremiah && *chapter==17 && *verse <= 27 { true }
    else if book==&BibleBook::Jeremiah && *chapter==18 && *verse <= 23 { true }
    else if book==&BibleBook::Jeremiah && *chapter==19 && *verse <= 15 { true }
    else if book==&BibleBook::Jeremiah && *chapter==20 && *verse <= 18 { true }
    else if book==&BibleBook::Jeremiah && *chapter==21 && *verse <= 14 { true }
    else if book==&BibleBook::Jeremiah && *chapter==22 && *verse <= 30 { true }
    else if book==&BibleBook::Jeremiah && *chapter==23 && *verse <= 40 { true }
    else if book==&BibleBook::Jeremiah && *chapter==24 && *verse <= 10 { true }
    else if book==&BibleBook::Jeremiah && *chapter==25 && *verse <= 38 { true }
    else if book==&BibleBook::Jeremiah && *chapter==26 && *verse <= 24 { true }
    else if book==&BibleBook::Jeremiah && *chapter==27 && *verse <= 22 { true }
    else if book==&BibleBook::Jeremiah && *chapter==28 && *verse <= 17 { true }
    else if book==&BibleBook::Jeremiah && *chapter==29 && *verse <= 32 { true }
    else if book==&BibleBook::Jeremiah && *chapter==30 && *verse <= 24 { true }
    else if book==&BibleBook::Jeremiah && *chapter==31 && *verse <= 40 { true }
    else if book==&BibleBook::Jeremiah && *chapter==32 && *verse <= 44 { true }
    else if book==&BibleBook::Jeremiah && *chapter==33 && *verse <= 26 { true }
    else if book==&BibleBook::Jeremiah && *chapter==34 && *verse <= 22 { true }
    else if book==&BibleBook::Jeremiah && *chapter==35 && *verse <= 19 { true }
    else if book==&BibleBook::Jeremiah && *chapter==36 && *verse <= 32 { true }
    else if book==&BibleBook::Jeremiah && *chapter==37 && *verse <= 21 { true }
    else if book==&BibleBook::Jeremiah && *chapter==38 && *verse <= 28 { true }
    else if book==&BibleBook::Jeremiah && *chapter==39 && *verse <= 18 { true }
    else if book==&BibleBook::Jeremiah && *chapter==40 && *verse <= 16 { true }
    else if book==&BibleBook::Jeremiah && *chapter==41 && *verse <= 18 { true }
    else if book==&BibleBook::Jeremiah && *chapter==42 && *verse <= 22 { true }
    else if book==&BibleBook::Jeremiah && *chapter==43 && *verse <= 13 { true }
    else if book==&BibleBook::Jeremiah && *chapter==44 && *verse <= 30 { true }
    else if book==&BibleBook::Jeremiah && *chapter==45 && *verse <= 5 { true }
    else if book==&BibleBook::Jeremiah && *chapter==46 && *verse <= 28 { true }
    else if book==&BibleBook::Jeremiah && *chapter==47 && *verse <= 7 { true }
    else if book==&BibleBook::Jeremiah && *chapter==48 && *verse <= 47 { true }
    else if book==&BibleBook::Jeremiah && *chapter==49 && *verse <= 39 { true }
    else if book==&BibleBook::Jeremiah && *chapter==50 && *verse <= 46 { true }
    else if book==&BibleBook::Jeremiah && *chapter==51 && *verse <= 64 { true }
    else if book==&BibleBook::Jeremiah && *chapter==52 && *verse <= 34 { true }
    else if book==&BibleBook::Lamentations && *chapter==1 && *verse <= 22 { true }
    else if book==&BibleBook::Lamentations && *chapter==2 && *verse <= 22 { true }
    else if book==&BibleBook::Lamentations && *chapter==3 && *verse <= 66 { true }
    else if book==&BibleBook::Lamentations && *chapter==4 && *verse <= 22 { true }
    else if book==&BibleBook::Lamentations && *chapter==5 && *verse <= 22 { true }
    else if book==&BibleBook::Ezekiel && *chapter==1 && *verse <= 28 { true }
    else if book==&BibleBook::Ezekiel && *chapter==2 && *verse <= 10 { true }
    else if book==&BibleBook::Ezekiel && *chapter==3 && *verse <= 27 { true }
    else if book==&BibleBook::Ezekiel && *chapter==4 && *verse <= 17 { true }
    else if book==&BibleBook::Ezekiel && *chapter==5 && *verse <= 17 { true }
    else if book==&BibleBook::Ezekiel && *chapter==6 && *verse <= 14 { true }
    else if book==&BibleBook::Ezekiel && *chapter==7 && *verse <= 27 { true }
    else if book==&BibleBook::Ezekiel && *chapter==8 && *verse <= 18 { true }
    else if book==&BibleBook::Ezekiel && *chapter==9 && *verse <= 11 { true }
    else if book==&BibleBook::Ezekiel && *chapter==10 && *verse <= 22 { true }
    else if book==&BibleBook::Ezekiel && *chapter==11 && *verse <= 25 { true }
    else if book==&BibleBook::Ezekiel && *chapter==12 && *verse <= 28 { true }
    else if book==&BibleBook::Ezekiel && *chapter==13 && *verse <= 23 { true }
    else if book==&BibleBook::Ezekiel && *chapter==14 && *verse <= 23 { true }
    else if book==&BibleBook::Ezekiel && *chapter==15 && *verse <= 8 { true }
    else if book==&BibleBook::Ezekiel && *chapter==16 && *verse <= 63 { true }
    else if book==&BibleBook::Ezekiel && *chapter==17 && *verse <= 24 { true }
    else if book==&BibleBook::Ezekiel && *chapter==18 && *verse <= 32 { true }
    else if book==&BibleBook::Ezekiel && *chapter==19 && *verse <= 14 { true }
    else if book==&BibleBook::Ezekiel && *chapter==20 && *verse <= 49 { true }
    else if book==&BibleBook::Ezekiel && *chapter==21 && *verse <= 32 { true }
    else if book==&BibleBook::Ezekiel && *chapter==22 && *verse <= 31 { true }
    else if book==&BibleBook::Ezekiel && *chapter==23 && *verse <= 49 { true }
    else if book==&BibleBook::Ezekiel && *chapter==24 && *verse <= 27 { true }
    else if book==&BibleBook::Ezekiel && *chapter==25 && *verse <= 17 { true }
    else if book==&BibleBook::Ezekiel && *chapter==26 && *verse <= 21 { true }
    else if book==&BibleBook::Ezekiel && *chapter==27 && *verse <= 36 { true }
    else if book==&BibleBook::Ezekiel && *chapter==28 && *verse <= 26 { true }
    else if book==&BibleBook::Ezekiel && *chapter==29 && *verse <= 21 { true }
    else if book==&BibleBook::Ezekiel && *chapter==30 && *verse <= 26 { true }
    else if book==&BibleBook::Ezekiel && *chapter==31 && *verse <= 18 { true }
    else if book==&BibleBook::Ezekiel && *chapter==32 && *verse <= 32 { true }
    else if book==&BibleBook::Ezekiel && *chapter==33 && *verse <= 33 { true }
    else if book==&BibleBook::Ezekiel && *chapter==34 && *verse <= 31 { true }
    else if book==&BibleBook::Ezekiel && *chapter==35 && *verse <= 15 { true }
    else if book==&BibleBook::Ezekiel && *chapter==36 && *verse <= 38 { true }
    else if book==&BibleBook::Ezekiel && *chapter==37 && *verse <= 28 { true }
    else if book==&BibleBook::Ezekiel && *chapter==38 && *verse <= 23 { true }
    else if book==&BibleBook::Ezekiel && *chapter==39 && *verse <= 29 { true }
    else if book==&BibleBook::Ezekiel && *chapter==40 && *verse <= 49 { true }
    else if book==&BibleBook::Ezekiel && *chapter==41 && *verse <= 26 { true }
    else if book==&BibleBook::Ezekiel && *chapter==42 && *verse <= 20 { true }
    else if book==&BibleBook::Ezekiel && *chapter==43 && *verse <= 27 { true }
    else if book==&BibleBook::Ezekiel && *chapter==44 && *verse <= 31 { true }
    else if book==&BibleBook::Ezekiel && *chapter==45 && *verse <= 25 { true }
    else if book==&BibleBook::Ezekiel && *chapter==46 && *verse <= 24 { true }
    else if book==&BibleBook::Ezekiel && *chapter==47 && *verse <= 23 { true }
    else if book==&BibleBook::Ezekiel && *chapter==48 && *verse <= 35 { true }
    else if book==&BibleBook::Daniel && *chapter==1 && *verse <= 21 { true }
    else if book==&BibleBook::Daniel && *chapter==2 && *verse <= 49 { true }
    else if book==&BibleBook::Daniel && *chapter==3 && *verse <= 30 { true }
    else if book==&BibleBook::Daniel && *chapter==4 && *verse <= 37 { true }
    else if book==&BibleBook::Daniel && *chapter==5 && *verse <= 31 { true }
    else if book==&BibleBook::Daniel && *chapter==6 && *verse <= 28 { true }
    else if book==&BibleBook::Daniel && *chapter==7 && *verse <= 28 { true }
    else if book==&BibleBook::Daniel && *chapter==8 && *verse <= 27 { true }
    else if book==&BibleBook::Daniel && *chapter==9 && *verse <= 27 { true }
    else if book==&BibleBook::Daniel && *chapter==10 && *verse <= 21 { true }
    else if book==&BibleBook::Daniel && *chapter==11 && *verse <= 45 { true }
    else if book==&BibleBook::Daniel && *chapter==12 && *verse <= 13 { true }
    else if book==&BibleBook::Hosea && *chapter==1 && *verse <= 11 { true }
    else if book==&BibleBook::Hosea && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Hosea && *chapter==3 && *verse <= 5 { true }
    else if book==&BibleBook::Hosea && *chapter==4 && *verse <= 19 { true }
    else if book==&BibleBook::Hosea && *chapter==5 && *verse <= 15 { true }
    else if book==&BibleBook::Hosea && *chapter==6 && *verse <= 11 { true }
    else if book==&BibleBook::Hosea && *chapter==7 && *verse <= 16 { true }
    else if book==&BibleBook::Hosea && *chapter==8 && *verse <= 14 { true }
    else if book==&BibleBook::Hosea && *chapter==9 && *verse <= 17 { true }
    else if book==&BibleBook::Hosea && *chapter==10 && *verse <= 15 { true }
    else if book==&BibleBook::Hosea && *chapter==11 && *verse <= 12 { true }
    else if book==&BibleBook::Hosea && *chapter==12 && *verse <= 14 { true }
    else if book==&BibleBook::Hosea && *chapter==13 && *verse <= 16 { true }
    else if book==&BibleBook::Hosea && *chapter==14 && *verse <= 9 { true }
    else if book==&BibleBook::Joel && *chapter==1 && *verse <= 20 { true }
    else if book==&BibleBook::Joel && *chapter==2 && *verse <= 32 { true }
    else if book==&BibleBook::Joel && *chapter==3 && *verse <= 21 { true }
    else if book==&BibleBook::Amos && *chapter==1 && *verse <= 15 { true }
    else if book==&BibleBook::Amos && *chapter==2 && *verse <= 16 { true }
    else if book==&BibleBook::Amos && *chapter==3 && *verse <= 15 { true }
    else if book==&BibleBook::Amos && *chapter==4 && *verse <= 13 { true }
    else if book==&BibleBook::Amos && *chapter==5 && *verse <= 27 { true }
    else if book==&BibleBook::Amos && *chapter==6 && *verse <= 14 { true }
    else if book==&BibleBook::Amos && *chapter==7 && *verse <= 17 { true }
    else if book==&BibleBook::Amos && *chapter==8 && *verse <= 14 { true }
    else if book==&BibleBook::Amos && *chapter==9 && *verse <= 15 { true }
    else if book==&BibleBook::Obadiah && *chapter==1 && *verse <= 21 { true }
    else if book==&BibleBook::Jonah && *chapter==1 && *verse <= 17 { true }
    else if book==&BibleBook::Jonah && *chapter==2 && *verse <= 10 { true }
    else if book==&BibleBook::Jonah && *chapter==3 && *verse <= 10 { true }
    else if book==&BibleBook::Jonah && *chapter==4 && *verse <= 11 { true }
    else if book==&BibleBook::Micah && *chapter==1 && *verse <= 16 { true }
    else if book==&BibleBook::Micah && *chapter==2 && *verse <= 13 { true }
    else if book==&BibleBook::Micah && *chapter==3 && *verse <= 12 { true }
    else if book==&BibleBook::Micah && *chapter==4 && *verse <= 13 { true }
    else if book==&BibleBook::Micah && *chapter==5 && *verse <= 15 { true }
    else if book==&BibleBook::Micah && *chapter==6 && *verse <= 16 { true }
    else if book==&BibleBook::Micah && *chapter==7 && *verse <= 20 { true }
    else if book==&BibleBook::Nahum && *chapter==1 && *verse <= 15 { true }
    else if book==&BibleBook::Nahum && *chapter==2 && *verse <= 13 { true }
    else if book==&BibleBook::Nahum && *chapter==3 && *verse <= 19 { true }
    else if book==&BibleBook::Habakkuk && *chapter==1 && *verse <= 17 { true }
    else if book==&BibleBook::Habakkuk && *chapter==2 && *verse <= 20 { true }
    else if book==&BibleBook::Habakkuk && *chapter==3 && *verse <= 19 { true }
    else if book==&BibleBook::Zephaniah && *chapter==1 && *verse <= 18 { true }
    else if book==&BibleBook::Zephaniah && *chapter==2 && *verse <= 15 { true }
    else if book==&BibleBook::Zephaniah && *chapter==3 && *verse <= 20 { true }
    else if book==&BibleBook::Haggai && *chapter==1 && *verse <= 15 { true }
    else if book==&BibleBook::Haggai && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Zechariah && *chapter==1 && *verse <= 21 { true }
    else if book==&BibleBook::Zechariah && *chapter==2 && *verse <= 13 { true }
    else if book==&BibleBook::Zechariah && *chapter==3 && *verse <= 10 { true }
    else if book==&BibleBook::Zechariah && *chapter==4 && *verse <= 14 { true }
    else if book==&BibleBook::Zechariah && *chapter==5 && *verse <= 11 { true }
    else if book==&BibleBook::Zechariah && *chapter==6 && *verse <= 15 { true }
    else if book==&BibleBook::Zechariah && *chapter==7 && *verse <= 14 { true }
    else if book==&BibleBook::Zechariah && *chapter==8 && *verse <= 23 { true }
    else if book==&BibleBook::Zechariah && *chapter==9 && *verse <= 17 { true }
    else if book==&BibleBook::Zechariah && *chapter==10 && *verse <= 12 { true }
    else if book==&BibleBook::Zechariah && *chapter==11 && *verse <= 17 { true }
    else if book==&BibleBook::Zechariah && *chapter==12 && *verse <= 14 { true }
    else if book==&BibleBook::Zechariah && *chapter==13 && *verse <= 9 { true }
    else if book==&BibleBook::Zechariah && *chapter==14 && *verse <= 21 { true }
    else if book==&BibleBook::Malachi && *chapter==1 && *verse <= 14 { true }
    else if book==&BibleBook::Malachi && *chapter==2 && *verse <= 17 { true }
    else if book==&BibleBook::Malachi && *chapter==3 && *verse <= 18 { true }
    else if book==&BibleBook::Malachi && *chapter==4 && *verse <= 6 { true }
    else if book==&BibleBook::Matthew && *chapter==1 && *verse <= 25 { true }
    else if book==&BibleBook::Matthew && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Matthew && *chapter==3 && *verse <= 17 { true }
    else if book==&BibleBook::Matthew && *chapter==4 && *verse <= 25 { true }
    else if book==&BibleBook::Matthew && *chapter==5 && *verse <= 48 { true }
    else if book==&BibleBook::Matthew && *chapter==6 && *verse <= 34 { true }
    else if book==&BibleBook::Matthew && *chapter==7 && *verse <= 29 { true }
    else if book==&BibleBook::Matthew && *chapter==8 && *verse <= 34 { true }
    else if book==&BibleBook::Matthew && *chapter==9 && *verse <= 38 { true }
    else if book==&BibleBook::Matthew && *chapter==10 && *verse <= 42 { true }
    else if book==&BibleBook::Matthew && *chapter==11 && *verse <= 30 { true }
    else if book==&BibleBook::Matthew && *chapter==12 && *verse <= 50 { true }
    else if book==&BibleBook::Matthew && *chapter==13 && *verse <= 58 { true }
    else if book==&BibleBook::Matthew && *chapter==14 && *verse <= 36 { true }
    else if book==&BibleBook::Matthew && *chapter==15 && *verse <= 39 { true }
    else if book==&BibleBook::Matthew && *chapter==16 && *verse <= 28 { true }
    else if book==&BibleBook::Matthew && *chapter==17 && *verse <= 27 { true }
    else if book==&BibleBook::Matthew && *chapter==18 && *verse <= 35 { true }
    else if book==&BibleBook::Matthew && *chapter==19 && *verse <= 30 { true }
    else if book==&BibleBook::Matthew && *chapter==20 && *verse <= 34 { true }
    else if book==&BibleBook::Matthew && *chapter==21 && *verse <= 46 { true }
    else if book==&BibleBook::Matthew && *chapter==22 && *verse <= 46 { true }
    else if book==&BibleBook::Matthew && *chapter==23 && *verse <= 39 { true }
    else if book==&BibleBook::Matthew && *chapter==24 && *verse <= 51 { true }
    else if book==&BibleBook::Matthew && *chapter==25 && *verse <= 46 { true }
    else if book==&BibleBook::Matthew && *chapter==26 && *verse <= 75 { true }
    else if book==&BibleBook::Matthew && *chapter==27 && *verse <= 66 { true }
    else if book==&BibleBook::Matthew && *chapter==28 && *verse <= 20 { true }
    else if book==&BibleBook::Mark && *chapter==1 && *verse <= 45 { true }
    else if book==&BibleBook::Mark && *chapter==2 && *verse <= 28 { true }
    else if book==&BibleBook::Mark && *chapter==3 && *verse <= 35 { true }
    else if book==&BibleBook::Mark && *chapter==4 && *verse <= 41 { true }
    else if book==&BibleBook::Mark && *chapter==5 && *verse <= 43 { true }
    else if book==&BibleBook::Mark && *chapter==6 && *verse <= 56 { true }
    else if book==&BibleBook::Mark && *chapter==7 && *verse <= 37 { true }
    else if book==&BibleBook::Mark && *chapter==8 && *verse <= 38 { true }
    else if book==&BibleBook::Mark && *chapter==9 && *verse <= 50 { true }
    else if book==&BibleBook::Mark && *chapter==10 && *verse <= 52 { true }
    else if book==&BibleBook::Mark && *chapter==11 && *verse <= 33 { true }
    else if book==&BibleBook::Mark && *chapter==12 && *verse <= 44 { true }
    else if book==&BibleBook::Mark && *chapter==13 && *verse <= 37 { true }
    else if book==&BibleBook::Mark && *chapter==14 && *verse <= 72 { true }
    else if book==&BibleBook::Mark && *chapter==15 && *verse <= 47 { true }
    else if book==&BibleBook::Mark && *chapter==16 && *verse <= 20 { true }
    else if book==&BibleBook::Luke && *chapter==1 && *verse <= 80 { true }
    else if book==&BibleBook::Luke && *chapter==2 && *verse <= 52 { true }
    else if book==&BibleBook::Luke && *chapter==3 && *verse <= 38 { true }
    else if book==&BibleBook::Luke && *chapter==4 && *verse <= 44 { true }
    else if book==&BibleBook::Luke && *chapter==5 && *verse <= 39 { true }
    else if book==&BibleBook::Luke && *chapter==6 && *verse <= 49 { true }
    else if book==&BibleBook::Luke && *chapter==7 && *verse <= 50 { true }
    else if book==&BibleBook::Luke && *chapter==8 && *verse <= 56 { true }
    else if book==&BibleBook::Luke && *chapter==9 && *verse <= 62 { true }
    else if book==&BibleBook::Luke && *chapter==10 && *verse <= 42 { true }
    else if book==&BibleBook::Luke && *chapter==11 && *verse <= 54 { true }
    else if book==&BibleBook::Luke && *chapter==12 && *verse <= 59 { true }
    else if book==&BibleBook::Luke && *chapter==13 && *verse <= 35 { true }
    else if book==&BibleBook::Luke && *chapter==14 && *verse <= 35 { true }
    else if book==&BibleBook::Luke && *chapter==15 && *verse <= 32 { true }
    else if book==&BibleBook::Luke && *chapter==16 && *verse <= 31 { true }
    else if book==&BibleBook::Luke && *chapter==17 && *verse <= 37 { true }
    else if book==&BibleBook::Luke && *chapter==18 && *verse <= 43 { true }
    else if book==&BibleBook::Luke && *chapter==19 && *verse <= 48 { true }
    else if book==&BibleBook::Luke && *chapter==20 && *verse <= 47 { true }
    else if book==&BibleBook::Luke && *chapter==21 && *verse <= 38 { true }
    else if book==&BibleBook::Luke && *chapter==22 && *verse <= 71 { true }
    else if book==&BibleBook::Luke && *chapter==23 && *verse <= 56 { true }
    else if book==&BibleBook::Luke && *chapter==24 && *verse <= 53 { true }
    else if book==&BibleBook::John && *chapter==1 && *verse <= 51 { true }
    else if book==&BibleBook::John && *chapter==2 && *verse <= 25 { true }
    else if book==&BibleBook::John && *chapter==3 && *verse <= 36 { true }
    else if book==&BibleBook::John && *chapter==4 && *verse <= 54 { true }
    else if book==&BibleBook::John && *chapter==5 && *verse <= 47 { true }
    else if book==&BibleBook::John && *chapter==6 && *verse <= 71 { true }
    else if book==&BibleBook::John && *chapter==7 && *verse <= 53 { true }
    else if book==&BibleBook::John && *chapter==8 && *verse <= 59 { true }
    else if book==&BibleBook::John && *chapter==9 && *verse <= 41 { true }
    else if book==&BibleBook::John && *chapter==10 && *verse <= 42 { true }
    else if book==&BibleBook::John && *chapter==11 && *verse <= 57 { true }
    else if book==&BibleBook::John && *chapter==12 && *verse <= 50 { true }
    else if book==&BibleBook::John && *chapter==13 && *verse <= 38 { true }
    else if book==&BibleBook::John && *chapter==14 && *verse <= 31 { true }
    else if book==&BibleBook::John && *chapter==15 && *verse <= 27 { true }
    else if book==&BibleBook::John && *chapter==16 && *verse <= 33 { true }
    else if book==&BibleBook::John && *chapter==17 && *verse <= 26 { true }
    else if book==&BibleBook::John && *chapter==18 && *verse <= 40 { true }
    else if book==&BibleBook::John && *chapter==19 && *verse <= 42 { true }
    else if book==&BibleBook::John && *chapter==20 && *verse <= 31 { true }
    else if book==&BibleBook::John && *chapter==21 && *verse <= 25 { true }
    else if book==&BibleBook::Acts && *chapter==1 && *verse <= 26 { true }
    else if book==&BibleBook::Acts && *chapter==2 && *verse <= 47 { true }
    else if book==&BibleBook::Acts && *chapter==3 && *verse <= 26 { true }
    else if book==&BibleBook::Acts && *chapter==4 && *verse <= 37 { true }
    else if book==&BibleBook::Acts && *chapter==5 && *verse <= 42 { true }
    else if book==&BibleBook::Acts && *chapter==6 && *verse <= 15 { true }
    else if book==&BibleBook::Acts && *chapter==7 && *verse <= 60 { true }
    else if book==&BibleBook::Acts && *chapter==8 && *verse <= 40 { true }
    else if book==&BibleBook::Acts && *chapter==9 && *verse <= 43 { true }
    else if book==&BibleBook::Acts && *chapter==10 && *verse <= 48 { true }
    else if book==&BibleBook::Acts && *chapter==11 && *verse <= 30 { true }
    else if book==&BibleBook::Acts && *chapter==12 && *verse <= 25 { true }
    else if book==&BibleBook::Acts && *chapter==13 && *verse <= 52 { true }
    else if book==&BibleBook::Acts && *chapter==14 && *verse <= 28 { true }
    else if book==&BibleBook::Acts && *chapter==15 && *verse <= 41 { true }
    else if book==&BibleBook::Acts && *chapter==16 && *verse <= 40 { true }
    else if book==&BibleBook::Acts && *chapter==17 && *verse <= 34 { true }
    else if book==&BibleBook::Acts && *chapter==18 && *verse <= 28 { true }
    else if book==&BibleBook::Acts && *chapter==19 && *verse <= 41 { true }
    else if book==&BibleBook::Acts && *chapter==20 && *verse <= 38 { true }
    else if book==&BibleBook::Acts && *chapter==21 && *verse <= 40 { true }
    else if book==&BibleBook::Acts && *chapter==22 && *verse <= 30 { true }
    else if book==&BibleBook::Acts && *chapter==23 && *verse <= 35 { true }
    else if book==&BibleBook::Acts && *chapter==24 && *verse <= 27 { true }
    else if book==&BibleBook::Acts && *chapter==25 && *verse <= 27 { true }
    else if book==&BibleBook::Acts && *chapter==26 && *verse <= 32 { true }
    else if book==&BibleBook::Acts && *chapter==27 && *verse <= 44 { true }
    else if book==&BibleBook::Acts && *chapter==28 && *verse <= 31 { true }
    else if book==&BibleBook::Romans && *chapter==1 && *verse <= 32 { true }
    else if book==&BibleBook::Romans && *chapter==2 && *verse <= 29 { true }
    else if book==&BibleBook::Romans && *chapter==3 && *verse <= 31 { true }
    else if book==&BibleBook::Romans && *chapter==4 && *verse <= 25 { true }
    else if book==&BibleBook::Romans && *chapter==5 && *verse <= 21 { true }
    else if book==&BibleBook::Romans && *chapter==6 && *verse <= 23 { true }
    else if book==&BibleBook::Romans && *chapter==7 && *verse <= 25 { true }
    else if book==&BibleBook::Romans && *chapter==8 && *verse <= 39 { true }
    else if book==&BibleBook::Romans && *chapter==9 && *verse <= 33 { true }
    else if book==&BibleBook::Romans && *chapter==10 && *verse <= 21 { true }
    else if book==&BibleBook::Romans && *chapter==11 && *verse <= 36 { true }
    else if book==&BibleBook::Romans && *chapter==12 && *verse <= 21 { true }
    else if book==&BibleBook::Romans && *chapter==13 && *verse <= 14 { true }
    else if book==&BibleBook::Romans && *chapter==14 && *verse <= 23 { true }
    else if book==&BibleBook::Romans && *chapter==15 && *verse <= 33 { true }
    else if book==&BibleBook::Romans && *chapter==16 && *verse <= 27 { true }
    else if book==&BibleBook::ICorinthians && *chapter==1 && *verse <= 31 { true }
    else if book==&BibleBook::ICorinthians && *chapter==2 && *verse <= 16 { true }
    else if book==&BibleBook::ICorinthians && *chapter==3 && *verse <= 23 { true }
    else if book==&BibleBook::ICorinthians && *chapter==4 && *verse <= 21 { true }
    else if book==&BibleBook::ICorinthians && *chapter==5 && *verse <= 13 { true }
    else if book==&BibleBook::ICorinthians && *chapter==6 && *verse <= 20 { true }
    else if book==&BibleBook::ICorinthians && *chapter==7 && *verse <= 40 { true }
    else if book==&BibleBook::ICorinthians && *chapter==8 && *verse <= 13 { true }
    else if book==&BibleBook::ICorinthians && *chapter==9 && *verse <= 27 { true }
    else if book==&BibleBook::ICorinthians && *chapter==10 && *verse <= 33 { true }
    else if book==&BibleBook::ICorinthians && *chapter==11 && *verse <= 34 { true }
    else if book==&BibleBook::ICorinthians && *chapter==12 && *verse <= 31 { true }
    else if book==&BibleBook::ICorinthians && *chapter==13 && *verse <= 13 { true }
    else if book==&BibleBook::ICorinthians && *chapter==14 && *verse <= 40 { true }
    else if book==&BibleBook::ICorinthians && *chapter==15 && *verse <= 58 { true }
    else if book==&BibleBook::ICorinthians && *chapter==16 && *verse <= 24 { true }
    else if book==&BibleBook::IICorinthians && *chapter==1 && *verse <= 24 { true }
    else if book==&BibleBook::IICorinthians && *chapter==2 && *verse <= 17 { true }
    else if book==&BibleBook::IICorinthians && *chapter==3 && *verse <= 18 { true }
    else if book==&BibleBook::IICorinthians && *chapter==4 && *verse <= 18 { true }
    else if book==&BibleBook::IICorinthians && *chapter==5 && *verse <= 21 { true }
    else if book==&BibleBook::IICorinthians && *chapter==6 && *verse <= 18 { true }
    else if book==&BibleBook::IICorinthians && *chapter==7 && *verse <= 16 { true }
    else if book==&BibleBook::IICorinthians && *chapter==8 && *verse <= 24 { true }
    else if book==&BibleBook::IICorinthians && *chapter==9 && *verse <= 15 { true }
    else if book==&BibleBook::IICorinthians && *chapter==10 && *verse <= 18 { true }
    else if book==&BibleBook::IICorinthians && *chapter==11 && *verse <= 33 { true }
    else if book==&BibleBook::IICorinthians && *chapter==12 && *verse <= 21 { true }
    else if book==&BibleBook::IICorinthians && *chapter==13 && *verse <= 14 { true }
    else if book==&BibleBook::Galatians && *chapter==1 && *verse <= 24 { true }
    else if book==&BibleBook::Galatians && *chapter==2 && *verse <= 21 { true }
    else if book==&BibleBook::Galatians && *chapter==3 && *verse <= 29 { true }
    else if book==&BibleBook::Galatians && *chapter==4 && *verse <= 31 { true }
    else if book==&BibleBook::Galatians && *chapter==5 && *verse <= 26 { true }
    else if book==&BibleBook::Galatians && *chapter==6 && *verse <= 18 { true }
    else if book==&BibleBook::Ephesians && *chapter==1 && *verse <= 23 { true }
    else if book==&BibleBook::Ephesians && *chapter==2 && *verse <= 22 { true }
    else if book==&BibleBook::Ephesians && *chapter==3 && *verse <= 21 { true }
    else if book==&BibleBook::Ephesians && *chapter==4 && *verse <= 32 { true }
    else if book==&BibleBook::Ephesians && *chapter==5 && *verse <= 33 { true }
    else if book==&BibleBook::Ephesians && *chapter==6 && *verse <= 24 { true }
    else if book==&BibleBook::Philippians && *chapter==1 && *verse <= 30 { true }
    else if book==&BibleBook::Philippians && *chapter==2 && *verse <= 30 { true }
    else if book==&BibleBook::Philippians && *chapter==3 && *verse <= 21 { true }
    else if book==&BibleBook::Philippians && *chapter==4 && *verse <= 23 { true }
    else if book==&BibleBook::Colossians && *chapter==1 && *verse <= 29 { true }
    else if book==&BibleBook::Colossians && *chapter==2 && *verse <= 23 { true }
    else if book==&BibleBook::Colossians && *chapter==3 && *verse <= 25 { true }
    else if book==&BibleBook::Colossians && *chapter==4 && *verse <= 18 { true }
    else if book==&BibleBook::IThessalonians && *chapter==1 && *verse <= 10 { true }
    else if book==&BibleBook::IThessalonians && *chapter==2 && *verse <= 20 { true }
    else if book==&BibleBook::IThessalonians && *chapter==3 && *verse <= 13 { true }
    else if book==&BibleBook::IThessalonians && *chapter==4 && *verse <= 18 { true }
    else if book==&BibleBook::IThessalonians && *chapter==5 && *verse <= 28 { true }
    else if book==&BibleBook::IThessalonians && *chapter==1 && *verse <= 12 { true }
    else if book==&BibleBook::IThessalonians && *chapter==2 && *verse <= 17 { true }
    else if book==&BibleBook::IThessalonians && *chapter==3 && *verse <= 18 { true }
    else if book==&BibleBook::ITimothy && *chapter==1 && *verse <= 20 { true }
    else if book==&BibleBook::ITimothy && *chapter==2 && *verse <= 15 { true }
    else if book==&BibleBook::ITimothy && *chapter==3 && *verse <= 16 { true }
    else if book==&BibleBook::ITimothy && *chapter==4 && *verse <= 16 { true }
    else if book==&BibleBook::ITimothy && *chapter==5 && *verse <= 25 { true }
    else if book==&BibleBook::ITimothy && *chapter==6 && *verse <= 21 { true }
    else if book==&BibleBook::IITimothy && *chapter==1 && *verse <= 18 { true }
    else if book==&BibleBook::IITimothy && *chapter==2 && *verse <= 26 { true }
    else if book==&BibleBook::IITimothy && *chapter==3 && *verse <= 17 { true }
    else if book==&BibleBook::IITimothy && *chapter==4 && *verse <= 22 { true }
    else if book==&BibleBook::Titus && *chapter==1 && *verse <= 16 { true }
    else if book==&BibleBook::Titus && *chapter==2 && *verse <= 15 { true }
    else if book==&BibleBook::Titus && *chapter==3 && *verse <= 15 { true }
    else if book==&BibleBook::Philemon && *chapter==1 && *verse <= 25 { true }
    else if book==&BibleBook::Hebrews && *chapter==1 && *verse <= 14 { true }
    else if book==&BibleBook::Hebrews && *chapter==2 && *verse <= 18 { true }
    else if book==&BibleBook::Hebrews && *chapter==3 && *verse <= 19 { true }
    else if book==&BibleBook::Hebrews && *chapter==4 && *verse <= 16 { true }
    else if book==&BibleBook::Hebrews && *chapter==5 && *verse <= 14 { true }
    else if book==&BibleBook::Hebrews && *chapter==6 && *verse <= 20 { true }
    else if book==&BibleBook::Hebrews && *chapter==7 && *verse <= 28 { true }
    else if book==&BibleBook::Hebrews && *chapter==8 && *verse <= 13 { true }
    else if book==&BibleBook::Hebrews && *chapter==9 && *verse <= 28 { true }
    else if book==&BibleBook::Hebrews && *chapter==10 && *verse <= 39 { true }
    else if book==&BibleBook::Hebrews && *chapter==11 && *verse <= 40 { true }
    else if book==&BibleBook::Hebrews && *chapter==12 && *verse <= 29 { true }
    else if book==&BibleBook::Hebrews && *chapter==13 && *verse <= 25 { true }
    else if book==&BibleBook::James && *chapter==1 && *verse <= 27 { true }
    else if book==&BibleBook::James && *chapter==2 && *verse <= 26 { true }
    else if book==&BibleBook::James && *chapter==3 && *verse <= 18 { true }
    else if book==&BibleBook::James && *chapter==4 && *verse <= 17 { true }
    else if book==&BibleBook::James && *chapter==5 && *verse <= 20 { true }
    else if book==&BibleBook::IPeter && *chapter==1 && *verse <= 25 { true }
    else if book==&BibleBook::IPeter && *chapter==2 && *verse <= 25 { true }
    else if book==&BibleBook::IPeter && *chapter==3 && *verse <= 22 { true }
    else if book==&BibleBook::IPeter && *chapter==4 && *verse <= 19 { true }
    else if book==&BibleBook::IPeter && *chapter==5 && *verse <= 14 { true }
    else if book==&BibleBook::IIPeter && *chapter==1 && *verse <= 21 { true }
    else if book==&BibleBook::IIPeter && *chapter==2 && *verse <= 22 { true }
    else if book==&BibleBook::IIPeter && *chapter==3 && *verse <= 18 { true }
    else if book==&BibleBook::IJohn && *chapter==1 && *verse <= 10 { true }
    else if book==&BibleBook::IJohn && *chapter==2 && *verse <= 29 { true }
    else if book==&BibleBook::IJohn && *chapter==3 && *verse <= 24 { true }
    else if book==&BibleBook::IJohn && *chapter==4 && *verse <= 21 { true }
    else if book==&BibleBook::IJohn && *chapter==5 && *verse <= 21 { true }
    else if book==&BibleBook::IIJohn && *chapter==1 && *verse <= 13 { true }
    else if book==&BibleBook::IIIJohn && *chapter==1 && *verse <= 14 { true }
    else if book==&BibleBook::Jude && *chapter==1 && *verse <= 25 { true }
    else if book==&BibleBook::Revelation && *chapter==1 && *verse <= 20 { true }
    else if book==&BibleBook::Revelation && *chapter==2 && *verse <= 29 { true }
    else if book==&BibleBook::Revelation && *chapter==3 && *verse <= 22 { true }
    else if book==&BibleBook::Revelation && *chapter==4 && *verse <= 11 { true }
    else if book==&BibleBook::Revelation && *chapter==5 && *verse <= 14 { true }
    else if book==&BibleBook::Revelation && *chapter==6 && *verse <= 17 { true }
    else if book==&BibleBook::Revelation && *chapter==7 && *verse <= 17 { true }
    else if book==&BibleBook::Revelation && *chapter==8 && *verse <= 13 { true }
    else if book==&BibleBook::Revelation && *chapter==9 && *verse <= 21 { true }
    else if book==&BibleBook::Revelation && *chapter==10 && *verse <= 11 { true }
    else if book==&BibleBook::Revelation && *chapter==11 && *verse <= 19 { true }
    else if book==&BibleBook::Revelation && *chapter==12 && *verse <= 17 { true }
    else if book==&BibleBook::Revelation && *chapter==13 && *verse <= 18 { true }
    else if book==&BibleBook::Revelation && *chapter==14 && *verse <= 20 { true }
    else if book==&BibleBook::Revelation && *chapter==15 && *verse <= 8 { true }
    else if book==&BibleBook::Revelation && *chapter==16 && *verse <= 21 { true }
    else if book==&BibleBook::Revelation && *chapter==17 && *verse <= 18 { true }
    else if book==&BibleBook::Revelation && *chapter==18 && *verse <= 24 { true }
    else if book==&BibleBook::Revelation && *chapter==19 && *verse <= 21 { true }
    else if book==&BibleBook::Revelation && *chapter==20 && *verse <= 15 { true }
    else if book==&BibleBook::Revelation && *chapter==21 && *verse <= 27 { true }
    else if book==&BibleBook::Revelation && *chapter==22 && *verse <= 21 { true }
    else { false }
}
